export const mySkills = [
    { name: "html", src: "html.png", alt: "HTML Logo" },
    { name: "css", src: "css.png", alt: "CSS Logo" },
    { name: "javaScript", src: "js.png", alt: "JavaScript Logo" },
    { name: "tailwind", src: "tailwind.png", alt: "Tailwindcss Logo" },
    { name: "react", src: "react.png", alt: "React.js Logo" },
    { name: "vue", src: "vue.png", alt: "vue.js Logo" },
    { name: "nuxt", src: "nuxt.png", alt: "nuxt.js Logo" },
      { name: "next", src: "next.png", alt: "Next.js Logo" },
    { name: "typescript", src: "ts.png", alt: "typescript Logo" },
    { name: "express", src: "express.png", alt: "express.js Logo" },
    // { name: "node", src: "node.png", alt: "node.js Logo" },
    { name: "python", src: "python.png", alt: "python Logo" },
    { name: "django", src: "django.png", alt: "django Logo" },
    { name: "git", src: "git.png", alt: "git Logo" },
    { name: "github", src: "github.png", alt: "github Logo" },
  ];